packages:
  - apps/*
  - packages/*

allowBuilds:
  '@clerk/shared': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  '@react-pdf/textkit@6.3.0': patches/@react-pdf__textkit@6.3.0.patch
  nextra-theme-docs@4.3.0: patches/nextra-theme-docs@4.3.0.patch
